### PR TITLE
Improve Windows support

### PR DESCRIPTION
**Pull request by iangudger**
Updates #12 (Windows support)
Updates #6 (eliminates the dependency on GCC for packaging function.zip)

### CODE REVIEW

**Comment by iangudger** [comment]
@albertog, want to try this out?

**Comment by iangudger** [comment]
@ssttevee, this avoids compiling the native module when packaging for GCF which goes along nicely with your godev change.

**Comment by albertog** [comment]
yes I am interesting


2018-01-29 2:31 GMT+01:00 Ian Gudger <notifications@github.com>:

**Comment by ssttevee** [comment]
I haven't been able to get this to work, how did you set up your windows environment for this?

**Comment by ssttevee** [comment]
I haven't been able to get this to work, it just fails with a connection error. Is the execer module supposed to get compiled on the function instance?

**Comment by iangudger** [comment]
I downloaded the [Windows 10 trial](https://www.microsoft.com/en-us/windowsforbusiness/try) and installed it in VirtualBox. I then installed [Cygwin](https://cygwin.com/install.html) x64 with the optional `make` and `zip` packages (selectable during the install process) and [Node.js](https://nodejs.org/en/download/) for Windows 64-bit msi installer. Then, in the Cygwin Terminal (I think this was previously called the Cygwin Bash Shell) I ran `make`. The resulting zip worked fine on GCF.

**Comment by iangudger** [comment]
@ssttevee The execer module gets compiled by GCF during the initial deployment. In fact, we never include compiled node modules in the function.zip file: https://github.com/GoogleCloudPlatform/cloud-functions-go/blob/master/Makefile#L19

**Comment by ssttevee** [comment]
I should have noticed 😅

It seems to be working fine after reinstalling cygwin. It also works with msys2. I think it should work as long as the user has access to the make and zip commands in their environment, not necessarily restricted to a specific POSIX emulator.

It may be worthwhile to look into a native windows method using a [powershell command](https://docs.microsoft.com/en-us/powershell/module/Microsoft.PowerShell.Archive/Compress-Archive?view=powershell-5.0).

**Comment by iangudger** [comment]
@ssttevee

If you want to send a PR adding either PowerShell support or msys2 instructions, I will happily review it.

If this works and looks good, could you approve this PR?

**Pull request merged**
